import type { NextPage } from "next";
import Head from "next/head";

import LandingPage, { Contact, Footer, Pricing } from "./landing-page";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>School Super App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
        <Pricing />
        <Contact />
        <Footer />
      </main>
    </>
  );
};

export default Home;
