packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": 5.51.11
  "@trpc/client": 11.0.0-rc.467
  "@trpc/server": 11.0.0-rc.467
  "@trpc/react-query": 11.0.0-rc.467
  "@trpc/next": 11.0.0-rc.467
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
