name: Production Deploy

on:
  push:
    branches:
      - main
    paths:
      - "apps/conectaprof/**"

jobs:
  deploy:
    name: Deploy ConectaProf
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY_URL: ${{ secrets.CONECTAPROF_DEPLOY_URL }}
    steps:
      - name: Start deploy
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ env.DEPLOY_URL }}
