name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Beanstalk Deploy for flip-python
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: ${{ secrets.ANUA_DEPLOY_URL }}
    steps:
      - name: Start deploy
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ env.DEPLOY_URL }}
